package:
  name: bst
  version: 0.1

source:
  git_url: https://shjoshi@bitbucket.org/bmapdev/bst.git
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python

  run:
    - python

test:
  # Python imports
  imports:

about:
  home: https://bitbucket.org/bmapdev/bst
  license: Lesser General Public License (LGPL) or BSD